controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    falcon_10_controller:
      type: forward_command_controller/ForwardCommandController
    
    falcon_11_controller:
      type: forward_command_controller/ForwardCommandController

    falcon_12_controller:
      type: forward_command_controller/ForwardCommandController

    falcon_13_controller:
      type: forward_command_controller/ForwardCommandController

    arm_position_controller:
      type: position_controllers/JointGroupPositionController

    bucket_position_controller:
      type: position_controllers/JointGroupPositionController

falcon_10_controller:
  ros__parameters:
    joints:
      - FL_Wheel_Joint
    interface_name: velocity

falcon_11_controller:
  ros__parameters:
    joints:
      - FR_Wheel_Joint
    interface_name: velocity

falcon_12_controller:
  ros__parameters:
    joints:
      - BL_Wheel_Joint
    interface_name: velocity

falcon_13_controller:
  ros__parameters:
    joints:
      - BR_Wheel_Joint
    interface_name: velocity

arm_position_controller:
  ros__parameters:
    joints: 
      - Arm_Joint

# NEW
bucket_position_controller:
  ros__parameters:
    joints: 
      - Bucket_Joint