int32 device_id
float64 bus_voltage
float64 output_current        # stator current (amps)
float64 output_voltage
float64 output_percent        # duty cycle
float64 temperature
float64 sensor_position              # rotations (Phoenix 6 native)
float64 sensor_velocity              # rotations/sec (Phoenix 6 native)
float64 closed_loop_error
bool temp_disable
bool error
bool restarted
float64 max_current