<?xml version="1.0"?>
<package format="3">
  <name>bluetooth</name>
  <version>0.0.1</version>
  <description>Bluetooth RFCOMM client</description>

  <maintainer email="andrewburroughs17@gmail.com">Andrew Burroughs</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>