<?xml version="1.0"?>
<package format="3">
  <name>perception</name>
  <version>1.0.0</version>
  <description>perception node</description>

  <maintainer email="andrewburroughs17@gmail.com">Andrew Burroughs</maintainer>
  <author>Andrew Burroughs</author>
  <license>none</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>messages</depend>
  <depend>utils</depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>

  <depend>sensor_msgs</depend>
  <depend>vision_msgs</depend>
  <depend>pcl_conversions</depend>
  <depend>libpcl-all-dev</depend>
  <depend>visualization_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_sensor_msgs</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>